### ISSUE TITLE
Retrain the selected model

### ISSUE THREAD

**Issue by nosqlgeek** [nosqlgeek/ai-meets-museum#15]

**Comment by nosqlgeek** [comment]
Model training can be pretty complex, so I would propose the following approach for our project:

1. Select a pre-trained model
2. Do some retraining if the time allows it
3. Only train a model from scratch if we aren't happy with the results of step 1. or step 2.

**Comment by stephanschorer** [comment]
## ToDos

- [x] python code for model training
- [ ] implementing cuda support
- [ ] testing different pytorch models

**Comment by stephanschorer** [comment]
we did not retrain our model, but it could be a good starting point
