### ISSUE TITLE
python code to split Dataset for training model

### ISSUE THREAD

**Issue by stephanschorer** [nosqlgeek/ai-meets-museum#21]
Split Dataset into testing and training data

## ToDos

- [x] python code for dataset split
- [ ] waiting for input list containing filename,label

**Comment by stephanschorer** [comment]
- [ ] implementing cuda support

**Comment by stephanschorer** [comment]
we did not retrain our model, but that could be a good starting point in the future

there is already some code - look at
https://github.com/nosqlgeek/ai-meets-museum/blob/imageClassification/src/tools/imageClassification/splitDataset.py
https://github.com/nosqlgeek/ai-meets-museum/blob/imageClassification/src/tools/imageClassification/trainModel.py
